name: AWS OIDC Advanced Workflow

on:
  push:
    branches:
      - main

jobs:
  aws-oidc-advanced:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Allows reading the repo contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::703671897239:role/OIDC-GitHub
          aws-region: us-east-1

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      - name: List S3 Buckets
        run: aws s3 ls

      - name: Upload a File to S3
        run: |
          echo "This is a test file" > testfile.txt
          aws s3 cp testfile.txt s3://s3-oidc-cicd/

      - name: Deploy AWS Lambda Function
        run: |
          zip lambda_function.zip lambda_function.py
          aws lambda update-function-code --function-name your-lambda-function-name --zip-file fileb://lambda_function.zip